export const EXPANDNOTIFICATION = "EXPANDNOTIFICATION";
export const UPDATENOTIFICATIONS = "UPDATENOTIFICATIONS";
export const UPDATENOTIFICATIONDATA = "UPDATENOTIFICATIONDATA";
// Auth Reducers
export const UPDATEACCESSTOKEN = "SETACCESSTOKEN";
export const UPDATEUSERDATA = "UPDATEUSERDATA";
export const UPDATEORGANIZATION = "UPDATEORGANIZATION";
export const UPDATELOADER = "UPDATELOADER";
export const UPDATELOCATION = "UPDATELOCATION";
export const UPDATEMENU = "EXPAND_MENU";
export const UPDATESEARCHBOX = "EXPAND_SEARCH";
export const UPDATELIVEVEHICLE = "UPDATELIVEVEHICLE";
export const UPDATELIVEVEHICLES = "UPDATELIVEVEHICLES";
export const UPDATEACTIVETRACKVEHICLE = "UPDATEACTIVETRACKVEHICLE";
export const UPDATEGLOBALSEARCHQUERY = "UPDATEGLOBALSEARCHQUERY";

//Analytics Responses
export const UPDATEANALYTIC = "UPDATEANALYTIC";

//Vehicle Responses
export const UPDATEDVEHICLES = "UPDATEDVEHICLES";

//Geofence Responses
export const UPDATEDGEOFENCE = "UPDATEDGEOFENCE";
export const UPDATEDGEOFENCEAREA = "UPDATEDGEOFENCEAREA";
export const UPDATEDGEOFENCEROUTECREATE = "UPDATEDGEOFENCEROUTECREATE";

//FuelGroup Responses
export const UPDATEFUELGROUPS = "UPDATEFUELGROUPS";
export const UPDATESELECTEDGROUP = "UPDATESELECTEDGROUP";

//Group Responses
export const UPDATEGROUPVEHICLES = "UPDATEGROUPVEHICLES";

//Tracker Responses
export const UPDATETRACKER = "UPDATETRACKER";

//Driver Responses
export const UPDATEDRIVER = "UPDATEDRIVER";

//Maintenance Responses
export const UPDATEOILCHANGE = "UPDATEOILCHANGE";
export const UPDATETIRECHANGE = "UPDATETIRECHANGE";
export const UPDATEOTHERCHANGE = "UPDATEOTHERCHANGE";

// FUEL RANGE
export const UPDATE_FUELRANGE = "UPDATE_FUELRANGE";

// FUEL Permissions
export const UPDATEPERMISSIONS = "UPDATEPERMISSIONS";

// FUEL Organization All
export const UPDATEORGANIZATIONUSERS = "UPDATEORGANIZATIONUSERS";
export const UPDATESELECTEDGEOFENCE = "UPDATESELECTEDGEOFENCE";

//Clear Redux
export const RESETAUTHREDUCER = "RESETAUTHREDUCER";
export const RESETTRACKREDUCER = "RESETTRACKREDUCER";

// Roles
export const UPDATEROLES = "UPDATEROLES";
export const UPDATESEARCHRESULT = "UPDATESEARCHRESULT";